package highlight

// buildLexerMap mirrors the Pygments lexer alias map from
// PhutilPygmentsSyntaxHighlighter::getPygmentsLexerNameFromLanguageName
// to ensure PHP sends the same language names and gets correct results.
//
// The keys are case-sensitive, exactly as the PHP table is; see the
// mixed-case group at the bottom and resolveLexer for why.
//
// Target names are spelled exactly as PHP spells them, even where Chroma
// accepts a synonym ("rb" not "ruby", "coffee-script" not "coffeescript"), so
// the two tables stay diffable. The only entries that deviate are the ones
// where the PHP spelling would break: they carry a comment saying so.
func buildLexerMap() map[string]string {
	return map[string]string{
		"adb":             "ada",
		"ads":             "ada",
		"ahkl":            "ahk",
		"as":              "as3",
		"asax":            "aspx-vb",
		"ascx":            "aspx-vb",
		"ashx":            "aspx-vb",
		"asm":             "nasm",
		"asmx":            "aspx-vb",
		"aspx":            "aspx-vb",
		"autodelegate":    "myghty",
		"autohandler":     "mason",
		"aux":             "tex",
		"axd":             "aspx-vb",
		"b":               "brainfuck",
		"bas":             "vb.net",
		"bf":              "brainfuck",
		"bmx":             "blitzmax",
		"c++":             "cpp",
		"c++-objdump":     "cpp-objdump",
		"cc":              "cpp",
		"cfc":             "cfm",
		"cfg":             "ini",
		"cfml":            "cfm",
		"cl":              "common-lisp",
		"clj":             "clojure",
		"cmd":             "bat",
		"coffee":          "coffee-script",
		"cs":              "csharp",
		"csh":             "tcsh",
		"cw":              "redcode",
		"cxx":             "cpp",
		"cxx-objdump":     "cpp-objdump",
		"darcspatch":      "dpatch",
		"def":             "modula2",
		"dhandler":        "mason",
		"di":              "d",
		"duby":            "rb",
		"dyl":             "dylan",
		"ebuild":          "bash",
		"eclass":          "bash",
		"el":              "common-lisp",
		"eps":             "postscript",
		"erl":             "erlang",
		"erl-sh":          "erl",
		"f":               "fortran",
		"f90":             "fortran",
		"feature":         "Cucumber",
		"fhtml":           "velocity",
		"flx":             "felix",
		"flxh":            "felix",
		"frag":            "glsl",
		"g":               "antlr", // PHP: "antlr-ruby", absent from Chroma
		"gdc":             "gooddata-cl",
		"gemspec":         "rb",
		"geo":             "glsl",
		"gnumakefile":     "make",
		"h":               "c",
		"h++":             "cpp",
		"hh":              "cpp",
		"hpp":             "cpp",
		"hql":             "sql",
		"hrl":             "erlang",
		"hs":              "haskell",
		"htaccess":        "apacheconf",
		"htm":             "html",
		"hxx":             "cpp",
		"hy":              "hybris",
		"hyb":             "hybris",
		"ik":              "ioke",
		"inc":             "pov",
		"j":               "objective-j",
		"jbst":            "duel",
		"kid":             "genshi",
		"ksh":             "bash",
		"less":            "css",
		"lgt":             "logtalk",
		"lisp":            "common-lisp",
		"ll":              "llvm",
		"m":               "objective-c",
		"mak":             "make",
		"makefile":        "make",
		"man":             "groff",
		"mao":             "mako",
		"mc":              "mason",
		"md":              "minid",
		"mhtml":           "mason",
		"mi":              "mason",
		"ml":              "ocaml",
		"mli":             "ocaml",
		"mll":             "ocaml",
		"mly":             "ocaml",
		"mm":              "objective-c",
		"mo":              "modelica",
		"mod":             "modula2",
		"moo":             "moocode",
		"mu":              "mupad",
		"myt":             "myghty",
		"ns2":             "newspeak",
		"pas":             "delphi",
		"patch":           "diff",
		"phtml":           "html+php",
		"pl":              "prolog",
		"plot":            "gnuplot",
		"plt":             "gnuplot",
		"pm":              "perl",
		"po":              "pot",
		"pp":              "puppet",
		"pro":             "prolog",
		"proto":           "protobuf",
		"ps":              "postscript",
		"pxd":             "cython",
		"pxi":             "cython",
		"py":              "python",
		"pyw":             "python",
		"pyx":             "cython",
		"r":               "rebol",
		"r3":              "rebol",
		"rake":            "rb",
		"rakefile":        "rb",
		"rbw":             "rb",
		"rbx":             "rb",
		"rest":            "rst",
		"rl":              "ragel", // PHP: "ragel-em", absent from Chroma
		"robot":           "robotframework",
		"rout":            "rconsole",
		"rss":             "xml",
		"s":               "gas",
		"sc":              "python",
		"scm":             "scheme",
		"sconscript":      "python",
		"sconstruct":      "python",
		"scss":            "css",
		"sh":              "bash",
		"sh-session":      "console",
		"spt":             "cheetah",
		"sqlite3-console": "sqlite3",
		"st":              "smalltalk",
		"sv":              "verilog", // PHP: "v", which is V/vlang in Chroma, not Verilog
		"tac":             "python",
		"tmpl":            "cheetah",
		"toc":             "tex",
		"tpl":             "smarty",
		"txt":             "text",
		"vapi":            "vala",
		"vb":              "vb.net",
		"vert":            "glsl",
		"vhd":             "vhdl",
		"vimrc":           "vim",
		"vm":              "velocity",
		"weechatlog":      "irc",
		"wlua":            "lua",
		"wsdl":            "xml",
		"xhtml":           "html",
		"xqy":             "xquery",
		"xsd":             "xml",
		"xsl":             "xslt",
		"xslt":            "xml",
		"yml":             "yaml",
		"rs":              "rust",
		"ts":              "typescript",
		"tsx":             "typescriptreact",
		"jsx":             "jsx",
		"kt":              "kotlin",
		"kts":             "kotlin",
		"swift":           "swift",
		"gradle":          "groovy",
		"tf":              "terraform",
		"hcl":             "terraform",
		"dockerfile":      "docker",
		"containerfile":   "docker",
		"toml":            "toml",
		"graphql":         "graphql",
		"gql":             "graphql",

		// Mixed-case keys, mirroring the PHP table verbatim. PHP looks the
		// language up with a plain idx() on a case-sensitive array, and
		// PhutilDefaultSyntaxHighlighterEngine::getLanguageFromFilename()
		// hands over the extension with its original case, so "foo.R" really
		// arrives as "R". Two of these differ from their lowercase twin and
		// must not be folded together:
		//
		//   "R" is the R language while "r" is REBOL
		//   "S" is the R language while "s" is GAS assembly
		//
		// Chroma has no "rebol" lexer, so "r" falls through to content
		// analysis; that matches what PHP asks for as closely as Chroma can.
		// The rest resolve the same either way and are listed only to keep
		// this table diffable against the PHP one.
		"ASM":         "nasm",
		"G":           "antlr", // "antlr-ruby" in PHP; Chroma only has "antlr"
		"GNUmakefile": "make",
		"Makefile":    "make",
		"R":           "splus", // Chroma alias of its R lexer
		"Rakefile":    "rb",
		"Rout":        "rconsole", // no Chroma equivalent; falls back
		"S":           "splus",
		"SConscript":  "python",
		"SConstruct":  "python",
	}
}
