CREATE TABLE IF NOT EXISTS search_projection_source_job (
 namespace VARBINARY(64) NOT NULL, jobID VARBINARY(64) NOT NULL,
 backendID VARBINARY(64) NOT NULL, generationID VARBINARY(64) NOT NULL,
 catalog LONGTEXT NOT NULL, createdEpoch BIGINT NOT NULL,
 PRIMARY KEY(namespace,jobID)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS search_projection_source_shard (
 namespace VARBINARY(64) NOT NULL, jobID VARBINARY(64) NOT NULL,
 className VARBINARY(128) NOT NULL, upperID BIGINT NOT NULL, cursorID BIGINT NOT NULL DEFAULT 0,
 status VARBINARY(16) NOT NULL DEFAULT 'scanning', pages BIGINT UNSIGNED NOT NULL DEFAULT 0,
 materialized BIGINT UNSIGNED NOT NULL DEFAULT 0, missing BIGINT UNSIGNED NOT NULL DEFAULT 0,
 noEngine BIGINT UNSIGNED NOT NULL DEFAULT 0, leaseOwner VARBINARY(64) NOT NULL DEFAULT '',
 leaseEpoch BIGINT UNSIGNED NOT NULL DEFAULT 0, leaseExpires BIGINT NOT NULL DEFAULT 0,
 nextAttempt BIGINT NOT NULL DEFAULT 0,
 PRIMARY KEY(namespace,jobID,className), KEY key_pending(namespace,status,nextAttempt,leaseExpires)
) ENGINE=InnoDB;
